name: rnbf
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - brotlipy=0.7.0=py38h27cfd23_1003
  - ca-certificates=2021.9.30=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=4.0.0=py38h06a4308_1003
  - conda-package-handling=1.7.3=py38h27cfd23_1
  - cryptography=3.4.7=py38hd23ed53_0
  - idna=2.10=pyhd3eb1b0_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libspatialindex=1.9.3=h2531618_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - ruamel_yaml=0.15.100=py38h27cfd23_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - tqdm=4.62.0=pyhd3eb1b0_1
  - tzdata=2021a=h5d7bf9c_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wheel=0.37.0=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
      - absl-py==0.13.0
      - addict==2.4.0
      - anyio==3.6.1
      - argon2-cffi==20.1.0
      - attrs==21.2.0
      - autoprop==3.0.0
      - babel==2.10.3
      - backcall==0.2.0
      - beautifulsoup4==4.10.0
      - bleach==4.0.0
      - cachetools==4.2.2
      - catkin-pkg==0.4.23
      - click==8.1.2
      - cmake==3.25.0
      - colorlog==5.0.1
      - colour==0.1.5
      - cvxpy==1.3.2
      - cycler==0.10.0
      - cython==0.29.24
      - debugpy==1.4.1
      - decorator==5.0.9
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - distro==1.6.0
      - docutils==0.17.1
      - ecos==2.0.12
      - empy==3.3.4
      - entrypoints==0.3
      - fastjsonschema==2.16.1
      - filelock==3.3.1
      - freetype-py==2.2.0
      - fsspec==2024.2.0
      - future==0.18.2
      - gdown==4.4.0
      - gitdb==4.0.9
      - gitpython==3.1.27
      - glooey==0.3.5
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.5
      - gputil==1.4.0
      - grpcio==1.39.0
      - h5py==3.4.0
      - huggingface-hub==0.20.3
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.5
      - imgviz==1.2.6
      - importlib-metadata==4.12.0
      - ipdb==0.13.9
      - ipykernel==6.2.0
      - ipython==7.26.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.6.3
      - jedi==0.18.0
      - jinja2==3.1.2
      - joblib==1.0.1
      - json5==0.9.8
      - jsonpatch==1.32
      - jsonpointer==2.2
      - jsonschema==3.2.0
      - jupyter-client==6.1.12
      - jupyter-core==4.7.1
      - jupyter-packaging==0.12.2
      - jupyter-server==1.18.1
      - jupyterlab==3.4.4
      - jupyterlab-pygments==0.1.2
      - jupyterlab-server==2.15.0
      - jupyterlab-widgets==1.0.0
      - kiwisolver==1.3.1
      - lit==15.0.7
      - llvmlite==0.37.0
      - lxml==4.6.3
      - markdown==3.3.4
      - markupsafe==2.0.1
      - matplotlib==3.4.3
      - matplotlib-inline==0.1.2
      - mesh-to-sdf==0.0.14
      - mistune==0.8.4
      - more-itertools==8.8.0
      - mplcursors==0.5.2
      - mpmath==1.2.1
      - msgpack==1.0.2
      - nbclassic==0.4.3
      - nbclient==0.5.4
      - nbconvert==6.5.0
      - nbformat==5.4.0
      - nest-asyncio==1.5.1
      - netifaces==0.11.0
      - networkx==2.2
      - notebook==6.4.3
      - notebook-shim==0.1.0
      - numba==0.54.1
      - numpy==1.20.3
      - oauthlib==3.1.1
      - open3d==0.14.1
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - ordered-set==4.0.2
      - osqp==0.6.3
      - packaging==21.0
      - pandas==1.4.3
      - pandocfilters==1.4.3
      - parso==0.8.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pika==1.2.1
      - pillow==9.1.1
      - plotly==5.3.1
      - plyfile==0.7.4
      - prometheus-client==0.11.0
      - prompt-toolkit==3.0.19
      - protobuf==3.17.3
      - ptyprocess==0.7.0
      - py-vox-io==0.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycollada==0.6
      - pydot==1.4.2
      - pyglet==1.5.19
      - pygments==2.10.0
      - pyhocon==0.3.58
      - pyopengl==3.1.0
      - pyparsing==2.4.7
      - pyqt5-qt5==5.15.14
      - pyqt5-sip==12.15.0
      - pyrealsense2==2.54.2.5684
      - pyrender==0.1.45
      - pyrsistent==0.18.0
      - python-dateutil==2.8.2
      - pytransform3d==3.13.0
      - pytz==2022.1
      - pywavelets==1.1.1
      - pyyaml==5.4.1
      - pyzmq==22.2.1
      - qdldl==0.1.7.post0
      - requests-oauthlib==1.3.0
      - rospkg==1.3.0
      - rsa==4.7.2
      - rtree==0.9.7
      - scikit-image==0.17.2
      - scikit-learn==0.24.2
      - scipy==1.7.1
      - scs==3.2.3
      - send2trash==1.8.0
      - setuptools==68.2.2
      - shapely==1.7.1
      - shiboken2==5.15.2.1
      - signature-dispatch==0.2.0
      - sklearn==0.0
      - smmap==5.0.0
      - sniffio==1.2.0
      - soupsieve==2.2.1
      - svg-path==4.1
      - sympy==1.8
      - tenacity==8.0.1
      - terminado==0.11.1
      - testpath==0.5.0
      - threadpoolctl==2.2.0
      - tifffile==2021.8.8
      - tinycss2==1.1.1
      - toml==0.10.2
      - tomlkit==0.11.1
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchfile==0.1.0
      - torchvision==0.15.2+cu118
      - tornado==6.1
      - traitlets==5.3.0
      - trimesh==3.9.28
      - triton==2.0.0
      - typeguard==2.12.1
      - typing-extensions==3.10.0.2
      - urdfpy==0.0.22
      - vecrec==0.3.0
      - video-cli==1.3.1
      - visdom==0.1.8.9
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==1.2.3
      - werkzeug==2.0.1
      - widgetsnbextension==3.5.1
      - xxhash==2.0.2
      - zipp==3.8.1
prefix: /home/coslam/anaconda3/envs/rnbf
